@startuml "Classes Diagram"

class Connect4
class Game
class Coordenate
class GameView
class Turn
class Token
class Board
class BoardView
class Player

Connect4 *--> Player
Connect4 *--> Game
Game .left> GameView
Game -> Player
Game *--> Board
Game *--> Turn
Game .-> BoardView
BoardView .> Board
Player ..> Token
Game *--> Token
Board *--> Coordenate

@enduml