@startuml "Activity Diagram - Choose players"

start
repeat
:Choose player type "R";
repeat while (Is valid player type) is (false)
repeat
:Choose player type "Y";
repeat while (Is valid player type) is (false)
stop
@enduml