@startuml "Component Diagram"

component Frontend
component Backend

interface Console

Frontend -- Console
Backend -- Console

note "Al code is in the same local folders. No chance for more components" as N1

@enduml