@startuml "Object Diagram"

object c4 {
  - game = Game()
  - gameView = GameView()
  - messages = Messages()
}
object game {
  - turn = 0
  + NUMBER_WINNER_TOKENS = 4
  + NUMBER_PLAYERS = 2
  + COLORS = [`R`, `Y`]
  + board = Board()
  + players = Players()
}
object board {
  - board = [
    [` `, `1`, `2`, `3`, `4`, `5`, `6`, `7`],
    [ `1`, `_`, `_`, `_`, `_`, `_`, `_`, `_`],
    [ `2`, `_`, `_`, `_`, `_`, `_`, `_`, `_`],
    [ `3`, `_`, `_`, `_`, `_`, `_`, `_`, `_`],
    [ `4`, `_`, `_`, `_`, `_`, `_`, `_`, `_`],
    [ `5`, `_`, `_`, `_`, `_`, `_`, `_`, `_`],
    [ `6`, `_`, `_`, `_`, `_`, `_`, `_`, `_`]
    ]
  + NUMBER_ROWS = 6
  + NUMBER_COLUMNS = 7
  + DELIMITER = `|`
  + EMPTY_CELL = `_`
  + line = Line()
}
object players {
  - players = [HumanPlayer, HumanPlayer]
}
c4 *--> game
game *--> board
game *--> players

@enduml